hosts: terraform-ansible
  task: 
  - name: criando arquivo
    copy: 
      dest: /home/ubuntu/index.html
      content: <h1>Vai durmi doidu! KKKKKKKK</h1> <br> </br> <div class="tenor-gif-embed" data-postid="21455562" data-share-method="host" data-aspect-ratio="1.33333" data-width="100%"><a href="https://tenor.com/view/goodnight-sleep-goodnight-meme-goodnight-bro-minecraft-gif-21455562">Goodnight Sleep GIF</a>from <a href="https://tenor.com/search/goodnight-gifs">Goodnight GIFs</a></div> <script type="text/javascript" async src="https://tenor.com/embed.js"></script>
  - name: criando servidor 
    shell: "nohup busybox httpd -f -p 8080 &"